environment:
  matrix:
    - nodejs_version: '8'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
init:
  - cmd: git config --global core.autocrlf input
  - cmd: node --version
  - cmd: npm --version
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: >-
      git clone https://github.com/saenzramiro/rambox-build.git %APPVEYOR_BUILD_FOLDER%\build\production\Rambox\

      npm install --only=prod

      cp -R node_modules %APPVEYOR_BUILD_FOLDER%\build\production\Rambox\
cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - node_modules
build_script:
  - cmd: npm run build:win
test: off
